---
all:
  children:
    httpd:
      hosts:
        clm-httpd-01.david-joo.sbx.hashidemos.io:
          ansible_host: 13.210.117.190
      vars:
        cert_service_type: httpd
    web_server:
      hosts: {}
      vars:
        cert_service_type: nginx
    tomcat:
      hosts: {}
      vars:
        cert_service_type: tomcat
